python3: can't open file '/app/ft_transcendence/manage.py': [Errno 2] No such file or directory
